[WIP] lingsamuel -> master
futurenda/fossil pull request #1
Opened 2017-07-19 08:49 UTC by lingsamuel

2017-07-21 11:55 UTC, lingsamuel commented
这功能要怎么用啊，推了几个新的commit

2017-07-21 12:06 UTC, zenozeng commented
@lingsamuel 我现在在写 API 的初始化配置文档，晚点 review 一下新的 commits

2017-07-21 13:08 UTC, lingsamuel commented
```
go build -o fossil
./fossil examples/input examples/output
```

2017-07-22 08:18 UTC, zenozeng requested changes
然后还需要实现：max_read_io_goroutines、Cancellation、基于 interface 的测试、用一下：onsi/ginkgo

2017-07-22 08:18 UTC, zenozeng commented on proc/ls.go
> +}
看一下 path/filepath 这个包的 Dir 之类的函数？

2017-07-22 08:18 UTC, zenozeng commented on main.go
> +		proc.FossilDir(proc.Paras{
这里要不还是把 Field Name 也写出来吧，感觉会更加清晰一些

2017-07-22 09:11 UTC, lingsamuel commented
max_read_io_goroutines 是什么意思，同时只有限量的goroutine在跑吗

2017-07-22 09:32 UTC, zenozeng commented
是的

On Sat, Jul 22, 2017, 17:11 Sarasa Kisaragi <notifications@github.com>
wrote:

> max_read_io_goroutines 是什么意思，同时只有限量的goroutine在跑吗
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/futurenda/fossil/pull/1#issuecomment-317169307>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACbTad9f8AFkBEA08dxahj5t6UPTe6rfks5sQbyrgaJpZM4OcavB>
> .
>

2017-08-18 10:04 UTC, zenozeng requested changes

2017-08-18 10:04 UTC, zenozeng commented on main.go
> +	. "github.com/zenozeng/fossil/proc"
包不对，另外不要在非测试里使用 import dot

2017-08-18 10:05 UTC, zenozeng commented on main.go
> +	. "github.com/zenozeng/fossil/proc"
另外去掉所有的 `\r\n`

2017-09-04 09:35 UTC, zenozeng commented
@lingsamuel package 改一下吧

2017-09-06 14:35 UTC, zenozeng approved these changes

2017-09-06 14:35 UTC, merged